import { Injectable } from '@angular/core';
import { Currency } from '@src/app/types/currency';

@Injectable({
  providedIn: 'root'
})
export class CurrencyService {
  constructor() {}

  getCurrencies(): Currency[] {
    return [
      { symbol: 'USD', currency: 'United States Dollars' },
      { symbol: 'EUR', currency: 'Euro' },
      { symbol: 'GBP', currency: 'United Kingdom Pounds' },
      { symbol: 'DZD', currency: 'Algeria Dinars' },
      { symbol: 'ARP', currency: 'Argentina Pesos' },
      { symbol: 'AUD', currency: 'Australia Dollars' },
      { symbol: 'ATS', currency: 'Austria Schillings' },
      { symbol: 'BSD', currency: 'Bahamas Dollars' },
      { symbol: 'BBD', currency: 'Barbados Dollars' },
      { symbol: 'BEF', currency: 'Belgium Francs' },
      { symbol: 'BMD', currency: 'Bermuda Dollars' },
      { symbol: 'BRR', currency: 'Brazil Real' },
      { symbol: 'BGL', currency: 'Bulgaria Lev' },
      { symbol: 'CAD', currency: 'Canada Dollars' },
      { symbol: 'CLP', currency: 'Chile Pesos' },
      { symbol: 'CNY', currency: 'China Yuan Renmimbi' },
      { symbol: 'CYP', currency: 'Cyprus Pounds' },
      { symbol: 'CSK', currency: 'Czech Republic Koruna' },
      { symbol: 'DKK', currency: 'Denmark Kroner' },
      { symbol: 'NLG', currency: 'Dutch Guilders' },
      { symbol: 'XCD', currency: 'Eastern Caribbean Dollars' },
      { symbol: 'EGP', currency: 'Egypt Pounds' },
      { symbol: 'FJD', currency: 'Fiji Dollars' },
      { symbol: 'FIM', currency: 'Finland Markka' },
      { symbol: 'FRF', currency: 'France Francs' },
      { symbol: 'DEM', currency: 'Germany Deutsche Marks' },
      { symbol: 'XAU', currency: 'Gold Ounces' },
      { symbol: 'GRD', currency: 'Greece Drachmas' },
      { symbol: 'HKD', currency: 'Hong Kong Dollars' },
      { symbol: 'HUF', currency: 'Hungary Forint' },
      { symbol: 'ISK', currency: 'Iceland Krona' },
      { symbol: 'INR', currency: 'India Rupees' },
      { symbol: 'IDR', currency: 'Indonesia Rupiah' },
      { symbol: 'IEP', currency: 'Ireland Punt' },
      { symbol: 'ILS', currency: 'Israel New Shekels' },
      { symbol: 'ITL', currency: 'Italy Lira' },
      { symbol: 'JMD', currency: 'Jamaica Dollars' },
      { symbol: 'JPY', currency: 'Japan Yen' },
      { symbol: 'JOD', currency: 'Jordan Dinar' },
      { symbol: 'KRW', currency: 'Korea (South) Won' },
      { symbol: 'LBP', currency: 'Lebanon Pounds' },
      { symbol: 'LUF', currency: 'Luxembourg Francs' },
      { symbol: 'MYR', currency: 'Malaysia Ringgit' },
      { symbol: 'MXP', currency: 'Mexico Pesos' },
      { symbol: 'NLG', currency: 'Netherlands Guilders' },
      { symbol: 'NZD', currency: 'New Zealand Dollars' },
      { symbol: 'NOK', currency: 'Norway Kroner' },
      { symbol: 'PKR', currency: 'Pakistan Rupees' },
      { symbol: 'XPD', currency: 'Palladium Ounces' },
      { symbol: 'PHP', currency: 'Philippines Pesos' },
      { symbol: 'XPT', currency: 'Platinum Ounces' },
      { symbol: 'PLZ', currency: 'Poland Zloty' },
      { symbol: 'PTE', currency: 'Portugal Escudo' },
      { symbol: 'ROL', currency: 'Romania Leu' },
      { symbol: 'RUR', currency: 'Russia Rubles' },
      { symbol: 'SAR', currency: 'Saudi Arabia Riyal' },
      { symbol: 'XAG', currency: 'Silver Ounces' },
      { symbol: 'SGD', currency: 'Singapore Dollars' },
      { symbol: 'SKK', currency: 'Slovakia Koruna' },
      { symbol: 'ZAR', currency: 'South Africa Rand' },
      { symbol: 'KRW', currency: 'South Korea Won' },
      { symbol: 'ESP', currency: 'Spain Pesetas' },
      { symbol: 'XDR', currency: 'Special Drawing Right (IMF)' },
      { symbol: 'SDD', currency: 'Sudan Dinar' },
      { symbol: 'SEK', currency: 'Sweden Krona' },
      { symbol: 'CHF', currency: 'Switzerland Francs' },
      { symbol: 'TWD', currency: 'Taiwan Dollars' },
      { symbol: 'THB', currency: 'Thailand Baht' },
      { symbol: 'TTD', currency: 'Trinidad and Tobago Dollars' },
      { symbol: 'TRL', currency: 'Turkey Lira' },
      { symbol: 'VEB', currency: 'Venezuela Bolivar' },
      { symbol: 'ZMK', currency: 'Zambia Kwacha' },
      { symbol: 'XCD', currency: 'Eastern Caribbean Dollars' },
      { symbol: 'XDR', currency: 'Special Drawing Right (IMF)' },
      { symbol: 'XAG', currency: 'Silver Ounces' },
      { symbol: 'XAU', currency: 'Gold Ounces' },
      { symbol: 'XPD', currency: 'Palladium Ounces' },
      { symbol: 'XPT', currency: 'Platinum Ounces' }
    ];
  }
}
