name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.15
        uses: actions/setup-node@v1
        with:
          node-version: "~10.15.3"
      - name: Install dependencies
        run: |
          google-chrome --version
          npm install
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1
        with:
          chromedriver-version: "81.0.4044.138"
      - name: Test client subdirectory
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          TESTING_CREDENTIALS: ${{ secrets.TESTING_CREDENTIALS }}
        run: |
          cd client
          npm run test
      - name: Test server subdirectory
        run: |
          cd server
          npm run test
