name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.15
        uses: actions/setup-node@v1
        with:
          node-version: "~10.15.3"
      - name: Install dependencies
        run: npm install
      - name: Run client unit tests
        run: |
          cd client
          npm run test:unit-test
      - name: Set webdriver version for client e2e testing
        run: |
          google-chrome --version
          cd client
          npm run setup-webdriver-manager
      - name: Run client e2e tests
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          TESTING_CREDENTIALS: ${{ secrets.TESTING_CREDENTIALS }}
          REDISCLOUD_URL: ${{ secrets.REDISCLOUD_URL }}
          CI: "true"
          CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
          API_KEY: ${{secrets.API_KEY}}
          API_SECRET: ${{ secrets.API_SECRET }}
          PORT: 3000
          JWT_HASH: ${{ secrets.JWT_HASH }}
          JWT_REFRESH_HASH: ${{ secrets.JWT_REFRESH_HASH }}
          SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          FRONT_END_URL: "http://localhost:4200"
          BACK_END_URL: "http://localhost:3000/api/v1"
          EMAIL_VERIFICATION_EMAIL_TEMPLATE: ${{ secrets.EMAIL_VERIFICATION_EMAIL_TEMPLATE }}
          MEMBER_WAS_ADDED_TO_FAMILY_EMAIL_TEMPLATE: ${{ secrets.MEMBER_WAS_ADDED_TO_FAMILY_EMAIL_TEMPLATE }}
          NODE_ENV: "staging"
          EMAILING_ENABLED: false
        run: |
          cd client
          npm run e2e
      - name: Archive e2e tests results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: e2e-tests-results
          path: client/e2e-tests-results
      - name: Run server tests
        run: |
          cd server
          npm run test
